name: heist_squad_x
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  get: ^3.26.0
  flutter_screenutil: ^4.0.4
  
  bonfire: ^0.9.0

  socket_io_client: ^0.9.12
  flame_splash_screen: ^0.0.1
  flutter_spinkit: ^5.0.0
  google_fonts: ^2.0.0
  animated_text_kit: ^4.1.0
  page_transition: ^1.1.7+6
  font_awesome_flutter: ^9.0.0
  fluttertoast: ^8.0.3
  wakelock: ^0.5.0+2
  audioplayers: ^0.18.3
  intl: ^0.17.0
  
  clipboard: ^0.1.3
  bubble: ^1.2.1
  auto_direction: ^0.0.4+1
  flutter_xlider: ^3.4.0
  tiledjsonreader: ^0.0.8

  # Firebase
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.2
  firebase_analytics: ^7.1.1

dependency_overrides:
  # audioplayers: 0.18.1
  # intl: 0.17.0
  shared_preferences: 2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/
    # - assets/images/
<<<<<<< HEAD
    - assets/images/weapons/
    - assets/images/icons/
    # - assets/images/tile/
    # - assets/images/items/
    # - assets/images/indoor/
    # - assets/images/sprites/player/
    - assets/audio/
    - assets/audio/breaking_wood/
=======
    # - assets/images/weapons/
    # - assets/images/icons/
    # - assets/images/tile/
    # - assets/images/items/
    - assets/audio/
    # - assets/images/indoor/
    # - assets/images/sprites/player/
>>>>>>> 1d0a6f2f738a8daa26e18f9295cd9adc1e0f379e
    - assets/logo/
    

    - assets/
    - assets/images/
<<<<<<< HEAD
    - assets/images/tiled/
    - assets/images/heroes/
    - assets/images/emotes/
    - assets/images/tiled/maps/
    - assets/images/tiled/maps/tilesets/
    - assets/images/tiled/tiles/tile/
    - assets/images/tiled/tiles/indoor/
    - assets/images/players/
=======
    - assets/images/tile/
    - assets/images/heroes/
    - assets/images/emotes/
>>>>>>> 1d0a6f2f738a8daa26e18f9295cd9adc1e0f379e

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages